routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/','HomePage@index')->name('page.home');

Route::get('/posts/{post}/{slug}','HomePage@show')->name('post.show');
Route::post('/post/{post}','HomePage@postComments')->name('post.comment');
Route::get('/topic/{topic}/{slug}','HomePage@topicPage')->name('topic.page');


Route::group(['prefix' => 'manager'], function () {
    Route::get('/','AdminHomeController@index');

    Route::resource('/topic', 'TopicController');
    Route::delete('/topic','TopicController@deleteAll');

    Route::resource('/posts', 'PostController');
    Route::delete('/posts','PostController@deleteAll');

});

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Model\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\ImageManagerStatic as Image;



class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $topics = Topic::all();
        return view('admin.topic.index',['topics'=>$topics]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.topic.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validated =$request->validate([
            'name'=>'required',
        ]);
        $imageUrl = 'default.jpg';
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            $img->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->text('CDIO4 e-commerce', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3-ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $topic = new Topic();
        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name);
        $topic->status = $request->status == "on"?1:0;
        $topic->image = $imageUrl;
        $topic->save();
        return redirect()->back()->with("success", "Successfull");


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        //
        return view('admin.topic.edit',['topic'=>$topic]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
        //
        $validated =$request->validate([
            'name'=>'required',
        ]);

        $imageUrl = null;
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            $img->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->text('CDIO4 e-commerce', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3-ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name);
        $topic->status = $request->status == "on"?1:0;
        if($imageUrl){
            $topic->image = $imageUrl;
        }
        $topic->save();
        return redirect()->back()->with("success", "Successfull");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        //
        Topic::find($topic->id)->delete();
        return redirect()->back()->with("deleted successfull");
    }



    // Delete checked topics ajax
    public function deleteAll(Request $request){

        $ids = $request->ids;
        $errors = null;
        try {
            //code...
            Topic::whereIn('id',$ids)->delete();
        } catch (\Throwable $th) {
            //throw $th;
            throw $errors  = $th;
        }

        return response()->json([
            'data'=>$errors
        ]);
    }
}

resources/views/admin/topic/create.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">

<div class="row" style="margin:10px">
    <div class="col-6">
        @if(session()->has('success'))
        <div class="alert alert-success" style="width:200ox;margin:auto">
            {{ session()->get('success') }}
        </div>
        @endif
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Topic</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('topic.store')}}" enctype="multipart/form-data">
                @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="inputName">Name</label>
                  <input name="name" type="name" class="form-control" id="inputName" placeholder="Enter name">
                </div>

                <div class="form-group">
                  <label for="exampleInputFile">Topic Image</label>
                  <div class="input-group">
                    <div class="custom-file" id="uploadForm">
                      <input name="image" id="file" type="file" class="custom-file-input" id="inputImage">
                      <label class="custom-file-label" for="inputImage">Choose Image</label>
                    </div>
                    <div class="input-group-append">
                      <span class="input-group-text" id="">Upload</span>
                    </div>
                  </div>
                </div>
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="inputStatus">
                  <label class="form-check-label" for="inputStatus">Status</label>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
    </div>
</div>

</div>
@endsection

resources/views/admin/topic/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">

<div class="row" style="margin:10px">
    <div class="col-6">
        @if(session()->has('success'))
        <div class="alert alert-success" style="width:200ox;margin:auto">
            {{ session()->get('success') }}
        </div>
        @endif
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Topic Edit</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('topic.update',$topic)}}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="inputName">Name</label>
                  <input value="{{$topic->name}}" name="name" type="name" class="form-control" id="inputName" placeholder="Enter name">
                </div>

                <div class="form-group">
                  <label for="exampleInputFile">Topic Image</label>
                  <div class="input-group">
                    <div class="custom-file" id="uploadForm">
                      <input name="image" id="file" type="file" class="custom-file-input" id="inputImage">
                      <label class="custom-file-label" for="inputImage">Choose Image</label>
                    </div>
                    <img name="image_prev" src="{{url($topic->image?$topic->image:"")}}" alt="" sizes="" srcset="">
                    <div class="input-group-append">
                      <span class="input-group-text" id="">Upload</span>
                    </div>
                  </div>
                </div>
                <div class="form-check">
                  <input checked type="checkbox" class="form-check-input" id="inputStatus">
                  <label class="form-check-label" for="inputStatus">Status</label>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
    </div>
</div>

</div>
@endsection

resources/views/admin/topic/index.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Topics</h3>

              <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                  <div class="input-group-append">
                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            {{--  --}}
            <div id="table-setting">
                <div class="row">
                    <div class="col-6">
                        <div style="display: flex;flex-direction:row;justify-content: flex-start;align-items: center">
                            <input type="checkbox" name="" id="topic-checkAll" style="margin-left:3%">
                            <input type="button" class="btn btn-danger" id="topic-deleteChecked" style="margin:10px" value="Delete All" />
                        </div>
                    </div>
                    <div class="col-6">
                        <div style="display: flex;flex-direction:row;justify-content: flex-end">
                            <a href="{{route('topic.create')}}" class="btn btn-success" style="margin:10px">Add new</a>
                        </div>
                    </div>
                </div>
            </div>
            {{--  --}}
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap" id="dataTable">
                <thead>
                  <tr>
                    <th>
                    </th>
                    <th>STT</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Setting</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($topics  as $key => $topic)
                    <tr>
                        <th>
                            <input value="{{$topic->id}}" type="checkbox" name="topic" id="topic-{{$topic->id}}">
                        </th>
                        <td>{{$key}}</td>
                        <td>{{$topic->name}}</td>
                        <td>{{$topic->slug}}</td>
                        <td>
                            <img width="120px" height="100px" src="{{$topic->image?$topic->image:""}}" alt="">
                        </td>
                        <td><span class="tag tag-success">{{$topic->status}}</span></td>
                        <td style="display: flex;justify-content: space-between">
                            <a href="{{route('topic.edit',$topic->id)}}"><i class="fas fa-edit" style="font-size:24px;color:blue"></i></a>
                            <a href="#" onclick="document.getElementById('formDelete-{{$topic->id}}').submit()"><i class="fas fa-trash-alt" style="font-size: 24px;color:red"></i></a>
                            <form action="{{route('topic.destroy',$topic->id)}}" method="POST" id="formDelete-{{$topic->id}}" style="display:none">
                                @method('DELETE')
                                @csrf
                                <button type="submit">Delete</button>
                            </form>
                        </td>

                    </tr>
                    @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
          {{-- <div style="width:300px;margin:auto">
              {{ $topics->links() }}
          </div> --}}
        </div>
      </div>
</div>

@endsection