routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/','HomePage@index')->name('page.home');

Route::get('/posts/{post}/{slug}','HomePage@show')->name('post.show');
Route::post('/post/{post}','HomePage@postComments')->name('post.comment');
Route::get('/topic/{topic}/{slug}','HomePage@topicPage')->name('topic.page');


Route::group(['prefix' => 'manager'], function () {
    Route::get('/','AdminHomeController@index');

    Route::resource('/topic', 'TopicController');
    Route::delete('/topic','TopicController@deleteAll');

    Route::resource('/posts', 'PostController');
    Route::delete('/posts','PostController@deleteAll');

});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Model\Post;
use App\Model\Tag;
use App\Model\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\ImageManagerStatic as Image;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::all();
        return view('admin.post.index',['posts'=>$posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $topics =Topic::all();
        $tags = Tag::all();
        return view('admin.post.create',['topics'=>$topics,'tags'=>$tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $validated = $request->validate([
            'topic'=>'required',
            'title'=>'required|max:255',
            'body'=>'required',
        ]);

        $imageUrl = 'default.jpg';
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            // $img->resize(null, 600, function ($constraint) {
            //     $constraint->aspectRatio();
            // });

            $img->text('elreading.club', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3.ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $post = new Post;
        $post->topic_id = $request->topic;
        $post->title = $request->title;
        $post->slug = Str::slug($request->title);
        $post->body = $request->body;
        $post->status = $request->status == "on"?1:0;
        $post->image = $imageUrl;
        $post->save();

        return redirect()->back()->with("success","successfull");

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
        $topics = Topic::all();
        $tags = Tag::all();
        return  view('admin.post.edit',['post'=>$post,'topics'=>$topics,'tags'=>$tags]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
        $validated = $request->validate([
            'topic'=>'required',
            'title'=>'required|max:255',
            'body'=>'required',
        ]);

        $imageUrl = 'default.jpg';
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            // $img->resize(200, 200, function ($constraint) {
            //     $constraint->aspectRatio();
            // });

            $img->text('elreading.club', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3.ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $post->topic_id = $request->topic;
        $post->title = $request->title;
        $post->slug = Str::slug($request->title);
        $post->introduction = $request->introduction;
        $post->body = $request->body;
        $post->status = $request->status == "on"?1:0;
        $post->image = $imageUrl;
        $post->save();

        return redirect()->back()->with("success","successfull");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        Post::find($post->id)->delete();
        return redirect()->back();
    }

    public function deleteAll(Request $request)
    {
        $ids = $request->ids;
        $errors = null;
        try {
            //code...
            Post::whereIn('id',$ids)->delete();
        } catch (\Throwable $th) {
            //throw $th;
            throw $errors  = $th;
        }

        return response()->json([
            'data'=>$errors
        ]);
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.master')

@section('content')
<style>
    .select2-container .select2-selection--single{
        height: auto;
    }
</style>
<div class="content-wrapper">
    <form role="form" method="POST" action="{{ route('posts.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="row" style="margin:10px">
            <div class="col-6">
                @if(session()->has('success'))
                <div class="alert alert-success" style="width:200ox;margin:auto">
                    {{ session()->get('success') }}
                </div>
                @endif
                <div class="card card-primary">
                    <div class="card-header">
                    <h3 class="card-title">Topic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <div class="form-group">
                            <label>Topic</label>
                            <select name="topic" class="form-control select2 select2-hidden-accessible js-select2-dropdown  @error('topic') is-invalid @enderror " style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option value="">-----Selecting Topic-----</option>
                                @foreach ($topics as $topic)
                                    <option value="{{$topic->id}}">{{$topic->name}}</option>
                                @endforeach
                            </select>
                            @error('topic')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="inputTitle">Title</label>
                            <input name="title" type="name" class="form-control  @error('title') is-invalid @enderror " id="inputTitle" placeholder="Enter Title">
                            @error('title')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputIntroduction">Introduction</label>
                            <textarea name="introduction" class="form-control  @error('introduction') is-invalid @enderror " id="inputIntroduction" rows="3" placeholder="Enter Introduction">

                            </textarea>
                            @error('introduction')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>


                        <div class="form-check">
                        <input name="status" type="checkbox" class="form-check-input" id="inputStatus">
                        <label class="form-check-label" for="inputStatus">Status</label>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card card-primary">
                    <div class="card-header">
                    <h3 class="card-title">Topic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <div class="form-group">
                            <label>Tag</label>
                            <select name="tags[]" multiple="multiple" class="form-control select2 select2-hidden-accessible js-select2-dropdown  @error('tag') is-invalid @enderror " style="width: 100%;color:red" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                @foreach ($tags as $tag)
                                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                                @endforeach
                            </select>

                            @error('tag')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Image</label>
                            <div class="custom-file" id="uploadForm">
                                <input name="image" id="file" type="file" class="custom-file-input  @error('image') is-invalid @enderror " id="inputImage">
                                <label class="custom-file-label" for="inputImage">Choose Image</label>
                                @error('image')
                                <span class="error invalid-feedback">{{$message}}</span>
                                @enderror
                            </div>
                        </div>

                </div>

            </div>
            </div>
            <div class="col-12">
                <div class="card-body pad">
                    <textarea name="body" id="editor1" rows="10" cols="80" class="@error('body') is-invalid @enderror">
                    </textarea>
                    @error('body')
                    <span class="error invalid-feedback">{{$message}}</span>
                    @enderror
                    <script>
                        // Replace the <textarea id="editor1"> with a CKEditor
                        // instance, using default configuration.
                        CKEDITOR.replace( 'editor1' );
                    </script>
                </div>
            </div>

        </div>
    </form>

</div>

@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<style>
    .select2-container .select2-selection--single{
        height: auto;
    }
</style>
<div class="content-wrapper">
    <form role="form" method="POST" action="{{ route('posts.update',$post->id)}}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row" style="margin:10px">
            <div class="col-6">
                @if(session()->has('success'))
                <div class="alert alert-success" style="width:200ox;margin:auto">
                    {{ session()->get('success') }}
                </div>
                @endif
                <div class="card card-primary">
                    <div class="card-header">
                    <h3 class="card-title">Topic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <div class="form-group">
                            <label>Topic</label>
                            <select name="topic" class="form-control select2 select2-hidden-accessible js-select2-dropdown  @error('topic') is-invalid @enderror " style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option value="">-----Selecting Topic-----</option>
                                @foreach ($topics as $topic)
                                    <option value="{{$topic->id}}" {{$post->topic->id ===$topic->id?"selected":""}} >{{$topic->name}}</option>
                                @endforeach
                            </select>
                            @error('topic')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="inputTitle">Title</label>
                            <input name="title" value="{{$post->title}}" type="name" class="form-control  @error('title') is-invalid @enderror " id="inputTitle" placeholder="Enter Title">
                            @error('title')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputIntroduction">Introduction</label>
                            <textarea name="introduction" class="form-control  @error('introduction') is-invalid @enderror " id="inputIntroduction" rows="3" placeholder="Enter Introduction">
                                {{$post->introduction}}
                            </textarea>
                            @error('introduction')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>


                        <div class="form-check">
                        <input name="status" type="checkbox" {{$post->status ===1?"checked":""}} class="form-check-input" id="inputStatus">
                        <label class="form-check-label" for="inputStatus">Status</label>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card card-primary">
                    <div class="card-header">
                    <h3 class="card-title">Topic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <div class="form-group">
                            <label>Tag</label>
                            <select name="tags[]" multiple="multiple" class="form-control select2 select2-hidden-accessible js-select2-dropdown  @error('tag') is-invalid @enderror " style="width: 100%;color:red" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                @foreach ($tags as $tag)
                                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                                @endforeach
                            </select>

                            @error('tag')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Image</label>
                            <div class="custom-file" id="uploadForm">
                                <input name="image" id="file" type="file" class="custom-file-input  @error('image') is-invalid @enderror " id="inputImage">
                                <label class="custom-file-label" for="inputImage">Choose Image</label>
                                <img src="{{$post->image}}" alt="">
                                @error('image')
                                <span class="error invalid-feedback">{{$message}}</span>
                                @enderror
                            </div>
                        </div>

                </div>

            </div>
            </div>
            <div class="col-12">
                <div class="card-body pad">
                    <textarea name="body" id="editor1" rows="10" cols="80" class="@error('body') is-invalid @enderror">
                    {{$post->body}}
                    </textarea>
                    @error('body')
                    <span class="error invalid-feedback">{{$message}}</span>
                    @enderror
                    <script>
                        // Replace the <textarea id="editor1"> with a CKEditor
                        // instance, using default configuration.
                        CKEDITOR.replace( 'editor1' );
                    </script>
                </div>
            </div>

        </div>
    </form>

</div>

@endsection

resources/views/admin/post/index.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">posts</h3>

              <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                  <div class="input-group-append">
                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            {{--  --}}
            <div id="table-setting">
                <div class="row">
                    <div class="col-6">
                        <div style="display: flex;flex-direction:row;justify-content: flex-start;align-items: center">
                            <input type="checkbox" name="" id="posts-checkAll" style="margin-left:3%">
                            <input type="button" class="btn btn-danger" id="posts-deleteChecked" style="margin:10px" value="Delete All" />
                        </div>
                    </div>
                    <div class="col-6">
                        <div style="display: flex;flex-direction:row;justify-content: flex-end">
                            <a href="{{route('posts.create')}}" class="btn btn-success" style="margin:10px">Add new</a>
                        </div>
                    </div>
                </div>
            </div>
            {{--  --}}
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap" id="dataTable">
                <thead>
                  <tr>
                    <th>
                    </th>
                    <th>STT</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Setting</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($posts  as $key => $post)
                    <tr style="cursor: pointer">
                        <th>
                            <input value="{{$post->id}}" type="checkbox" name="posts" id="post-{{$post->id}}">
                        </th>
                        <td>{{$key}}</td>
                        <td>{{$post->title}}</td>
                        <td>
                            <img width="120px" height="100px" src="{{$post->image?$post->image:""}}" alt="">
                        </td>
                        <td><span class="tag tag-success">{{$post->status}}</span></td>
                        <td style="display: flex;justify-content: space-between">
                            <a href="{{route('posts.edit',$post->id)}}"><i class="fas fa-edit" style="font-size:24px;color:blue"></i></a>
                            <a href="#" onclick="document.getElementById('formDelete-{{$post->id}}').submit()"><i class="fas fa-trash-alt" style="font-size: 24px;color:red"></i></a>
                            <form action="{{route('posts.destroy',$post->id)}}" method="POST" id="formDelete-{{$post->id}}" style="display:none">
                                @method('DELETE')
                                @csrf
                                <button type="submit">Delete</button>
                            </form>
                        </td>

                    </tr>
                    @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
          {{-- <div style="width:300px;margin:auto">
              {{ $posts->links() }}
          </div> --}}
        </div>
      </div>
</div>

@endsection